# NOTE: Custom image specification for freebsd is required until new version of cross is released.

[build.env]
passthrough = [
    "CARGO_INCREMENTAL",
    "RUST_BACKTRACE",
    "CARGO_TERM_COLOR",
]
